# Generated by Django 2.0.2 on 2018-02-27 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='hero',
        ),
    ]
