# Generated by Django 2.0.2 on 2018-02-28 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_auto_20180227_2144'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='time_end',
            field=models.DateTimeField(null=True),
        ),
    ]
