# Generated by Django 2.0.2 on 2018-02-28 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_session_time_end'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='hourly_rate',
            field=models.DecimalField(decimal_places=5, max_digits=20, null=True),
        ),
    ]
