# Generated by Django 2.0.2 on 2018-02-28 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_auto_20180228_0136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='hourly_rate',
            field=models.DecimalField(decimal_places=5, editable=False, max_digits=20, null=True),
        ),
        migrations.RemoveField(
            model_name='session',
            name='place',
        ),
        migrations.AddField(
            model_name='session',
            name='place',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tracker.Place'),
        ),
    ]
