# Generated by Django 2.0.2 on 2018-02-28 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0007_auto_20180228_0144'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='time_per_session',
            field=models.DurationField(null=True),
        ),
    ]
