# Generated by Django 2.0.2 on 2018-03-01 11:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0009_session_session_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='session_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
